temporalio/docker-builds

.github/workflows/docker-admin-tools.yml
.github/workflows/docker-auto-setup.yml
.github/workflows/docker-server.yml

Automates Release process:
- On creating Releases from https://github.com/temporalio/docker-builds/releases page, this will trigger the pipelines and publish corresponding semver images [auto-setup, server, admin-tools] to https://hub.docker.com/r/temporalio/
- Simplifies release process
- Supports ARM (and M1 macs)
- Includes new tctl https://github.com/temporalio/tctl
- Gives visibility into releases to external users
1. Closes 
~ mostly through testing the same process on ui-server https://github.com/temporalio/ui-server/releases/tag/v0.2.0

Automate docker images release process

---

.github/workflows/docker-server.yml

Switches quotes syntax in server per-commit pipeline
https://docs.github.com/en/actions/learn-github-actions/expressions#literals
Fixing pipeline 
1. Closes 
not tested, nektos/act works with both single and double quotes. Have to run in  GHA and rely on docs https://docs.github.com/en/actions/learn-github-actions/expressions#literals

Correct expressions syntax to fix server per-commit pipeline

---

.gitignore
admin-tools.Dockerfile
auto-setup.Dockerfile
develop.Dockerfile
docker/base-images/base-builder.Dockerfile
docker/base-images/base-ci-builder.Dockerfile
docker/base-images/base-server.Dockerfile
server.Dockerfile

Upgrade go version to the latest 1.17.6 to close https://github.com/temporalio/temporal/issues/2451.

Upgrade go to 1.17.6

---

.github/workflows/update-submodules.yml

- Commits into `main` instead of `master` when the input BRANCH == 'master'
- Stops hiding error if push is unsuccessful
on Temporal updates, it was trying to commit into master
```
git push origin master
error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/temporalio/docker-builds'
```
https://github.com/temporalio/docker-builds/runs/5210816039?check_suite_focus=true#step:5:17
1. Closes 

Commit into main instead of master

---

docker/base-images/base-admin-tools.Dockerfile
docker/base-images/base-server.Dockerfile

Removing vim from base container images
CVE
confirmed `vi` is still available _**if**_ needed.
1. Closes 
#28 
Confirmed through local docker run/exec/build
No

Removing vim, verified vi is available

---

.github/workflows/release-base-image.yml

Added a pipeline to release base-* image
Accepts:
* target - Target base image, one of: base-server, base-builder, base-ci-builder, base-admin-tools
* commit - Commit sha to build from
* tag - New tag for the image
Automating release process
1. Closes 
executed the script using `nektos/act`
```
[Release Base-* Docker image/build-push-images]   ❓  ::endgroup::
[Release Base-* Docker image/build-push-images]   ✅  Success - Build-Push Server image
```
in progress

Create Release pipeline for base-* images

---

admin-tools.Dockerfile
server.Dockerfile

Explicit `CGO_ENABLED=0` is removed because it is set by default https://github.com/temporalio/temporal/pull/2760.

Remove explicit CGO_ENABLED=0

---

docker/auto-setup.sh

It seems like the variable `DB_PORT` isn't passed to `temporal-sql-tool` when the DB is mysql. However, `temporal-sql-tool` does listen for `SQL_PORT` by default. The mismatch here makes it so that changing the port of MySQL doesn't work with the auto-setup docker image.
1. Closes 

Pass the `DB_PORT` in case of mysql

---

docker/base-images/base-admin-tools.Dockerfile
docker/base-images/base-builder.Dockerfile
docker/base-images/base-ci-builder.Dockerfile
docker/base-images/base-server.Dockerfile

Upgrade base images to use `alpine:3.16`.
To address security concerns.

Upgrade base images to use alpine:3.16

---

docker/base-images/base-admin-tools.Dockerfile

Remove `python2` dependency from `base-admin-tools`.
`python2` was removed from alpine 3.16: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.16.0.

Remove python2 dependency from base-admin-tools

---

docker/base-images/base-builder.Dockerfile
docker/base-images/base-ci-builder.Dockerfile
docker/base-images/base-server.Dockerfile

Bump go version to 1.19 on the base images.
These images are used as a base to build other images.
1. Closes 

Bump go version to 1.19 on the base images

---

.github/workflows/docker.yml
.github/workflows/release-all-base-image.yml
.github/workflows/release-base-image.yml

Moving Docker builds to GitHub-hosted larger 16-core runners.
Existing build performance is not satisfactory. We want to have faster builds.
1. Closes 
CI
No

Use larger GitHub-hosted runners for Docker builds

---

docker/entrypoint.sh

Use `getent hosts ${hostname}` instead of `hostname -i` to resolve our own IP address.
There appears to be a [bug with busybox](https://bugs.busybox.net/show_bug.cgi?id=15056) on Alpine where `hostname -i` throws a "Host not found" error when running on a pod in a k8s cluster using IPv6 -- using `getent hosts` instead correctly resolves the IP address.
1. Closes 
Successfully spun up a working Temporal cluster in an IPv6 k8s cluster after applying this change. Without this change, pods would start successfully, but workflows could not be started.
no

Fix entrypoint when running in IPv6

---

admin-tools.Dockerfile

Upgrade just this one package in admin-tools directly on release branch, so that we don't pull in other changes to base images.
CVE-2022-40674
1. Closes 
local build, verify expat version

Upgrade expat in admin-tools

---

.github/workflows/docker.yml
.github/workflows/release-all-base-image.yml
.github/workflows/release-base-image.yml

Changed GitHub runners to BuildJet.
BuildJet is 2x cheaper than GitHub-hosted runners.
https://buildjet.com/for-github-actions/docs/runners
1. Closes 
No
CI
No

Use BuildJet instead of GitHub-hosted larger runners

---

.github/workflows/docker.yml
.github/workflows/release-temporal.yml
.github/workflows/update-submodules.yml

Upgraded GitHub Actions to use Environment Files
The `set-output` command is deprecated and will be disabled soon. Upgraded to use Environment Files.
For more information, see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.
1. Closes 
No
3. How was this tested:
CI
No

Upgrade GitHub Actions to use Environment Files

---

.github/workflows/release-temporal.yml
src/go.mod
src/go.sum
src/release_temporal/main.go
src/release_temporal/main_test.go

Updated image tagging to follow semantic versioning: `<major>.<minor>.<patch>.<security>`
The current approach of not reusing tags and not following Image semantic versioning creates friction for image security patches as they require a new Temporal Server release.
This change enables us to reuse tags for security patches and use image semantic versioning for simple image upgrades.
After this change, we will start releasing security and other patches using the `security` version. For example: for the existing `temporalio/server:1.18.4` image, after we release a security patch, we will update these tags:
```
temporalio/server:1.18.4.<security>
temporalio/server:1.18.4
temporalio/server:1.18
temporalio/server:1
```
Then users can continue using `FROM temporalio/server:1.18.4` to get the …

Use semantic versioning tags for release images

---

.github/workflows/docker.yml
.github/workflows/release-all-base-image.yml
.github/workflows/release-base-image.yml

This reverts commit 5097fe65b2bc6fc1f6e2c8e90ae0a1370c6479d2.
Revert "Use BuildJet instead of GitHub-hosted larger runners (https://github.com/temporalio/docker-builds/pull/77)"
BuildJet is unreliable.
1. Closes 
No
3. How was this tested:
CI
No

Revert "Use BuildJet instead of GitHub-hosted larger runners (#77)"

---

.github/workflows/docker-build-only.yml
admin-tools.Dockerfile
server.Dockerfile

Create a workflow which can be called by other repos to *just* build a docker image of server, so that they can use it for testing a certain commit, etc, without needing a published image.
Draft while working through using it from the server repo w/ sdk-features.

Add callable workflow for only building the server image

---

.gitmodules
Makefile
admin-tools.Dockerfile
server.Dockerfile

Added `temporal` CLI into the Docker images
distribution of the new cli
1. Closes 
verified that `server`, `admin-tools` and `auto-setup` images have `temporal` executable under `/usr/local/bin`. Also that `temporal` is in the PATH 

Add Temporal CLI to docker images

---

.github/workflows/docker.yml

Added default timeout for the Docker Images job
Sometimes this job gets stuck for an unknown reason and is canceled by the default timeout, which is 360 mins (6 hours).
1. Closes 
No
CI
No

Add 30 mins timeout for the Docker images job

---

docker/start-temporal.sh
server.Dockerfile

- Remove the default for `SERVICES` env var, so that the server will use its own internal default (all configured services).
- Rewrite the logic in `start-temporal.sh` so it works without `SERVICES` set.
We want to be able to have one docker image that can run with internal-frontend, or not, depending on the config. This lets the server binary handle the default service set instead of hardcoding it here.
1. Closes 
manual testing

Remove default SERVICES var

---

docker/entrypoint.sh

Added a check for TEMPORAL_CLI_ADDRESS before setting it up.
It will be pointed to a different container for a multi-role setup.
1. Closes 
No
Locally
No

auto-setup: check TEMPORAL_CLI_ADDRESS before setting it up

---

admin-tools.Dockerfile

Users a non-root user for the admintools container.
Using a non-root user in containers reduces the chances of security issues.
Fixes #61

Run admintools container as non-root user.

---

docker/base-images/base-admin-tools.Dockerfile
docker/base-images/base-server.Dockerfile

Removed nsswitch.conf workaround for Alpine <3.16
Alpine 3.17 includes the file /etc/nsswitch.conf
```
% docker run --rm -it alpine:3.16 ls -l /etc/nsswitch.conf
ls: /etc/nsswitch.conf: No such file or directory
% docker run --rm -it alpine:3.17 ls -l /etc/nsswitch.conf
-rw-r--r--    1 root     root           205 Nov  4 14:43 /etc/nsswitch.conf
% docker run --rm -it alpine:3.17 cat /etc/nsswitch.conf
hosts: files dns
```
1. Closes 
No
```
make base-server
make base-builder
make base-admin-tools
```
No

Remove nsswitch.conf workaround

---

admin-tools.Dockerfile
server.Dockerfile

Bumped base-builder image to 1.12.0
Bumped base-server image to 1.13.0
Bumped base-admin-tools image to 1.10.0
Periodic maintenance.
1. Closes 
No
CI
No

Bump base image versions

---

docker/auto-setup.sh

Updated temporal CLI command.
Removed not defined the `--yes` option.
Before:
```
$ temporal operator search-attribute create --namespace "${DEFAULT_NAMESPACE}" --yes \
--name CustomKeywordField --type Keyword \
--name CustomStringField --type Text \
--name CustomTextField --type Text \
--name CustomIntField --type Int \
--name CustomDatetimeField --type Datetime \
--name CustomDoubleField --type Double \
--name CustomBoolField --type Bool
Incorrect Usage: flag provided but not defined: -yes
```
After:
```
$ temporal operator search-attribute create --namespace "${DEFAULT_NAMESPACE}" \
--name CustomKeywordField --type Keyword \
--name CustomStringField --type Text \
--name CustomTextField --type Text \
--name CustomIntField --type Int \
--name CustomDatetimeField --type Datetime \
--name …
```

Update temporal search-attribute command

---

admin-tools.Dockerfile
docker/base-images/base-admin-tools.Dockerfile

- Added `tini` to admin-tools's entrypoint
- Avoid 10 seconds delay on admin-tools container termination, due to incorrect SIGTERM handling by busybox's `tail` command (see below image for behavior before this PR)
More context
```
This is likely the result of the PID 1 signaling issue.
Inside a PID namespace the first process launched gets PID 1.
PID 1 is treated special by the kernel in that the default signal actions are to ignore, instead of exit.
Meaning that unless the application installs a signal handler,
SIGINT and SIGTERM won't cause the application to exit. (see http://lwn.net/Articles/532748/)
tail is a very basic utility, and does not install any signal handlers, so it ignores them.
The only thing that will kill it is SIGKILL (which is what docker stop will do after the 10 …
```

Avoid 10 seconds delay on admin-tools container termination

---

.github/workflows/docker.yml
Makefile
server.Dockerfile

Added Env variables with components versions:
```
$ make docker-server
...
$ docker inspect docker.io/temporalio/server:latest | jq '.[].Config.Env'
[
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
"TEMPORAL_HOME=/etc/temporal",
"TEMPORAL_SHA=1a479ad802abf3fc2de735ee3535a625fef5bc5",
"TCTL_SHA=46f3e20e26434e142f320a215be4ce21ba643a0",
"CLI_SHA=7c42c704522ad64ad7f3934538e3500dc175792"
]
$ git submodule status
7c42c704522ad64ad7f3934538e3500dc1757924 cli (v0.6.0-1-g7c42c70)
46f3e20e26434e142f320a215be4ce21ba643a01 tctl (v1.18.0-2-g46f3e20)
1a479ad802abf3fc2de735ee3535a625fef5bc5d temporal (v1.13.0-1564-g1a479ad80)
$ docker run --rm -it --entrypoint env docker.io/temporalio/server:latest
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin …
```

Save component versions in ENV variables

---

.gitmodules
Makefile
admin-tools.Dockerfile
server.Dockerfile

- Started installing the official latest CLI version instead of building on spot
- Removed CLI submodule
Consistency with the CLI releases, proper correlation when addressing support questions
1. Closes 
- Built an image locally and verified `temporal` command is available
- Verified that `which temporal` returns the same value 

Replace Temporal CLI build with official release version

---

.github/workflows/release-all-base-image.yml

Removed unnecessary new line.
```
ERROR: invalid tag "temporalio/base-ci-builder:1.9.2\\n": invalid reference format
```
1. Closes 
No
CI
No

Fix GHA GITHUB_OUTPUT variable

---

.github/workflows/release-all-base-image.yml

Updated matrix options
By mistake, the arch option `"linux/amd64,linux/arm64"` was treated as two separate options.
1. Closes 
No
GHA
No

Fix release-all-base-images GHA martix options

---

docker/auto-setup.sh
docker/entrypoint.sh

`TEMPORAL_CLI_ADDRESS` is deprecated, and its support will be removed in the future release.
Support both `TEMPORAL_CLI_ADDRESS` and `TEMPORAL_ADDRESS`.
The latest Temporal CLI has renamed those variables: https://github.com/temporalio/cli/releases/tag/v0.9.0
1. Closes 
No
CICD
No

Rename TEMPORAL_CLI_ADDRESS to TEMPORAL_ADDRESS

---

.github/workflows/docker.yml
Makefile
server.Dockerfile

Removed `CLI_SHA` env var from docker images.
After the CLI installation change, It's not used anymore.
1. Closes 
No
CICD
No

Remove CLI_SHA as it is not used anymore

---

src/image_tags/main.go
src/image_tags/main_test.go

Fixed tagging command.
Added tests.
Bugfix
```
Run tag=$(cd src; go run image_tags/main.go -org temporalio -repo "$REPO" bump "$BUMP")
tag=$(cd src; go run image_tags/main.go -org temporalio -repo "$REPO" bump "$BUMP")
echo "tag=$tag" >> $GITHUB_OUTPUT
shell: /usr/bin/bash -e {0}
env:
REPO: base-admin-tools
BUMP: minor
go: downloading github.com/Masterminds/semver/v3 v3.2.1
2023/06/12 19:14:22 Error parsing version: Invalid Semantic Version
exit status 1
```
It was failing for the version string `latest`.
1. Closes 
No
GHA
No

Fix tagging command and add tests

---

admin-tools.Dockerfile
server.Dockerfile

Upgraded base docker image versions
To use the latest versions.
```
docker-builds % (cd src; go run image_tags/main.go -org temporalio -repo "base-server" latest)
2023/06/12 13:27:00 Error parsing version: "latest". Invalid Semantic Version
1.15.0
docker-builds % (cd src; go run image_tags/main.go -org temporalio -repo "base-builder" latest)
2023/06/12 13:27:07 Error parsing version: "latest". Invalid Semantic Version
1.14.0
docker-builds % (cd src; go run image_tags/main.go -org temporalio -repo "base-admin-tools" latest)
2023/06/12 13:27:13 Error parsing version: "latest". Invalid Semantic Version
1.12.0
```
1. Closes 
No
CICD, GHA
No

Bump base images

---

admin-tools.Dockerfile
server.Dockerfile

- Enable bash competion for temporal cli in admin-tools
- Combine a few RUN lines into one
- Fix ownership of temporal binary
Make using admin-tools more pleasant
1. Closes 
manually (local docker build)

Enable bash competion for temporal cli in admin-tools

---

.github/workflows/update-submodules.yml

Updated GHA tokens for update-submodule jobs
No need for a separate token to trigger in-repo actions
1. Closes 
No
CI
No

Update update-submodules GHA

---

.github/workflows/release-temporal.yml
src/release_temporal/main.go
src/release_temporal/main_test.go

Fixed `latest` image updating.
Added support for updating major image tags.
During the previous release patching, we don't want to update the `latest` tag together with the major tag `1`. 
I.e., if we have the previous release of `1.20.3` and the latest release of `1.21.1`, then our docker images would point as such:
```
latest - v1.21.1
1      - v1.21.1
1.21   - v1.21.1
1.21.1 - v1.21.1
1.20   - v1.20.3
1.20.3 - v1.20.3
```
When updating the `1.20.4` release, we want this behavior and no other changes:
```
latest - v1.21.1
1      - v1.21.1
1.21   - v1.21.1
1.21.1 - v1.21.1
1.20   - v1.20.4 <--
1.20.3 - v1.20.3
1.20.4 - v1.20.4 <--
```
1. Closes 
No
Unit tests
No

Update image tagging to support previous release patching

---

admin-tools.Dockerfile

- Add bash-completion package to admin-tools only
Newer version of temporal cli will depend on this for shell completion
1. Closes 
manually with local docker build

Add bash-completion package to admin-tools

---

docker/base-images/base-builder.Dockerfile

The version of our golang image was bumped to provide Go version 1.21.
We have projects that would like to make use of the new functionality provided by this release.
1. Closes: N/A
2. How was this tested: CI
3. Any docs updates needed? No

Bump our go image to use 1.21

---

docker/base-images/base-ci-builder.Dockerfile
docker/base-images/base-server.Dockerfile
src/go.mod

The previous PR (#143) missed a few image upgrades. This PR makes up for that.
Thanks @mindaugasrukas for pointing it out.

Bump more Go versions to 1.21

---

admin-tools.Dockerfile
server.Dockerfile

We bumped Go to 1.21 and need to update to the new Docker image.
Without this, the feature tests fail for the Server repo.
1. Closes 

bump images to use Go 1.21

---

docker/auto-setup.sh

Disable xtrace in auto-setup.sh script.
It was leaking passwords.
1. Closes 
https://github.com/temporalio/temporal/issues/3022

Disable sh xtrace in auto-setup.sh script

---

docker/auto-setup.sh

This PR replaces #60. 
Arguments were added to `auto-setup.sh` which allow TLS terminated connections to Postres databases for schema setup.
Our database server requires TLS connections. 
1. Closes #59
This change only forwards arguments. I'm relying on the documentation of the command `temporal-sql-tool`. However, I have tested that command in an existing container to make sure the boolean flags work as expected and that arguments with empty strings as values are ignored.
It seems to me the code is the documentation. At least I found several links to the `auto-steup.sh` file in the [docs](https://docs.temporal.io/kb/all-the-ways-to-run-a-cluster).

Allow TLS configuration for Postgres DBs in auto-setup.sh

---

.github/workflows/docker.yml

Pushing container images requires credentials, which we won't have on PRs given this is a public repository.

Don't try to push images on PRs

---

admin-tools.Dockerfile
docker/base-images/README.md
server.Dockerfile

All images were bumped to use newer versions of our base-* images 
To address the recent curl vulnerability

Bump image versions to address curl vulnerability

---

.github/workflows/docker.yml

Commit ca055fd026d8ff82626fe42951580664f65f6bc5 was reverted
This broke our CI somehow, and actions stopped running against `main`

Revert "Don't try to push images on PRs (#151)"

---

docker/base-images/Makefile
docker/base-images/base-ci-builder.Dockerfile

Remove fossa install from `base-ci-builder`
We don't use fossa anymore, and it's actually pretty big.
1. Closes 

Remove fossa install step from base-ci-builder

---

.github/workflows/release-all-base-image.yml
docker/base-images/Makefile

I've updated our makefile and github actions to build a linux/arm64 version of base-ci-builder so those of us running arm laptops can run our buildkite actions locally
Shellcheck now has an arm64 binary so we're no longer stuck on linux/amd64

Build an arm64 image for base-ci-builder

---

.github/workflows/docker.yml

We no longer kick off a concourse action when build-push-images runs.
We're retiring concourse

Don't kick off concourse builds

---

.github/workflows/docker.yml
Makefile
admin-tools.Dockerfile
auto-setup.Dockerfile
docker-bake.hcl

I replaced all our manual image build steps with a [Docker bake file](https://docs.docker.com/build/bake/) so it's easier to manage. This will let me swap in depot---or anything else that is required for all image builds---with ease.
I'll take a look at doing the same for our base images in another PR later if it makes sense.
A declarative config file like this lets us change or add images without mucking about with the grody github actions yaml file. This will also let docker (or depot) manage parallelism and sharing better.
I ran the new `make verify-ci` target and it built the images successfully.

Use a docker bakefile to simplify CI

---

.github/workflows/docker.yml

We run the `bake` action twice now: once to load it locally, and a second time to push to the remote when requested.
You cannot specify these options together: https://github.com/temporalio/docker-builds/actions/runs/6880855010/job/18715940597

Separate push and load steps

---

.github/workflows/docker-build-only.yml
.github/workflows/docker.yml
.github/workflows/release-all-base-image.yml
.github/workflows/release-base-image.yml
.github/workflows/release-temporal.yml
admin-tools.Dockerfile
auto-setup.Dockerfile
server.Dockerfile

This preserves docker buildkit cache mounts between runs by [integrating with GHA's caching](https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api). While I was here I bumped the version of all the GHAs we use
This should improve the performance of our build pipelines and _hopefully_ keep them from timing out rebuilding things we've built many times before.

Cache docker builder cache between runs

---

.github/workflows/docker.yml
docker-bake.hcl

We need latest to be set _only_ when building against main, otherwise when we build a release image we can stomp the versions needed for nightly testing.
The bake file makes this pretty easy to do thankfully.

Only tag latest when we're building after a push to main

---

.github/workflows/docker.yml

Caching is now enabled for the cross-platform build where it's _really_ needed. I cleaned up how we specify the cache parameters as well so we're not copy-pasting a blob of text across multiple steps.
My overworked reviewer and I both missed this as we're obviously juggling too many things at once.

Enable caches for multiarch builds

---

docker/base-images/base-ci-builder.Dockerfile

I added `sed` to our base ci builder image.
We're beginning to use this for some nasty proto fixups and should just place it in the base image.

Add sed to base-ci-builder

---

.github/workflows/docker.yml
.github/workflows/release-all-base-image.yml
.github/workflows/release-base-image.yml
.github/workflows/release-temporal.yml
.github/workflows/update-latest-temporal.yml

We now use a dockerhub Personal Access Token (PAT) instead of the account password
Over the weekend security changed our docker account to require MFA, so our automated processes need to use the PAT instead of the password

Use the dockerhub PAT

---

.github/workflows/docker-build-only.yml

I updated the docker-build-only pipeline to tag latest and use the `temporaliotest` repo instead of `temporal`
So CI works. This pairs with https://github.com/temporalio/features/pull/386

Tag latest when building test images

---

.github/workflows/docker.yml
Makefile

We now correctly set the image tag when dispatched from GitHub
It was broken before
```
$ make COMMIT=a59209eeba62f1da800461044b23ce8b335e58c3 simulate-dispatch 2>/dev/null | rg IMAGE_TAG
[Build Docker Images/build-push-images        ]   ⚙  ::set-env:: IMAGE_TAG=sha-a59209e
```

Correctly set the SHA when dispatched from GitHub

---

docker/auto-setup.sh

Related to https://github.com/temporalio/temporal/pull/5305, this add `postgres12_pgx` as a valid value for the env `DB`
Support for `jackc/pgx` was added in #4913 but it wasn't possible to use it directly with `temporalio/auto-setup`

Add postgres12_pgx as DB type

---

docker/base-images/base-admin-tools.Dockerfile
docker/base-images/base-builder.Dockerfile
docker/base-images/base-ci-builder.Dockerfile
docker/base-images/base-server.Dockerfile

Alpine is upgraded from `3.18` to `3.19`
Addresses [CVE-2023-5363](https://nvd.nist.gov/vuln/detail/CVE-2023-5363)
This should also address [CVE-2023-39325](https://nvd.nist.gov/vuln/detail/CVE-2023-39325) as `dockerize` has [updated](https://github.com/jwilder/dockerize/commit/8f3785f7a523d776e680243a13263b324075b7f6) its `go.mod`, and `base-server.Dockerfile` [always pulls](https://github.com/temporalio/docker-builds/blob/2b1b5cad1964e2e16cd7c357b729cbd08d690924/docker/base-images/base-server.Dockerfile#L7-L11) the latest `main`.
1. Closes #180 
Ran `make test`
None

Update alpine to 3.19

---

admin-tools.Dockerfile
server.Dockerfile

Fixing `COPY` for adding `.git` directories.
https://github.com/temporalio/temporal/actions/runs/8299631664/job/22717105934?pr=5507
```
server.Dockerfile:27
--------------------
25 |     # Git info is needed for Go build to attach VCS information properly.
26 |     # See the `buildvcs` Go flag: https://pkg.go.dev/cmd/go
27 | >>> COPY ./.git ./.git
28 |     COPY ./.gitmodules ./.gitmodules
29 |     RUN --mount=type=cache,target=/root/.cache/go-build (cd ./temporal && make temporal-server)
--------------------
ERROR: failed to solve: source can't be a git ref for COPY
Error: buildx bake failed with: ERROR: failed to solve: source can't be a git ref for COPY
```
Might be related to https://github.com/moby/buildkit/pull/4326 and https://github.com/actions/runner-images/pull/9482
1. Closes 
2. …

fix `COPY .git` #2

---

.github/workflows/docker.yml
.gitignore
.gitmodules
Makefile
admin-tools.Dockerfile
docker/base-images/base-server.Dockerfile
server.Dockerfile

1. Cross-compilation is done outside of the docker container, and images are copying in pre-built binaries
2. All external dependencies are vendored using submodules instead of cloning (dockerize) or curling (cli)
Building this container now takes ~1m locally instead of over an hour on my aarch64 laptop.
I tested this locally by running `make build test`

Use go's native cross-compilation for binaries

---

.github/workflows/docker-build-only.yml
.github/workflows/docker.yml
Makefile

Our GHA workflows now use the makefile to build/push the image
The Makefile is our single source of truth for how to build these images; the GHA workflows should focus on environment setup.
I don't want to see failures like https://github.com/temporalio/temporal/actions/runs/8530026612?pr=5650 again

All docker image builds go through the makefile

---

.github/workflows/docker.yml

Build images from `cloud/*` branches too, as triggered by https://github.com/temporalio/temporal/pull/5696
So we can test them

Add cloud/* branches to docker workflow

---

docker/auto-setup.sh

Check if it's enabling ES, and avoid setting up visibility schemas in MySQL/PostgreSQL.
Adds a bit of flexibility if anyone wants to setup with MariaDB or CockroachDB for main storage and ES for visibility since the schema for visibility might not be compatible with those DBs.
1. Closes 

Check if ES is enabled before setting up visibility schema in MySQL/Postgres

---

.github/workflows/docker-build-only.yml
.github/workflows/docker.yml
.github/workflows/lint.yml
.github/workflows/release-all-base-image.yml
.github/workflows/release-base-image.yml
.github/workflows/release-temporal.yml
.github/workflows/update-submodules.yml

I updated the version of out-of-date GitHub actions as some of these will be deprecated later this year

Update GHA versions so CI stops complaining

---

.github/workflows/update-submodules.yml
Makefile

I added the option to specify a commit to our update submodule action
This will allow us to update to a specific release version for
repos (e.g. the cli) that don't have release branches

Update submodule to specific commit

---

.github/workflows/release-admin-tools.yml
.github/workflows/release-all-base-image.yml

Our admintools image is now tagged separately from the server images. It will no longer share a version with our server images
This allows us to release it more frequently as we want it updated when _either_ the server or our various debugging tools are updated
Release runbooks will be updated later today

Use a separate release tag for admintools

---

.github/workflows/release-admin-tools.yml

Our "release admintools" action now calculates the tag for you

Calculate admintools tag

---

.github/workflows/release-admin-tools.yml

New admin-tools tags will be `${server_tag}-${serial_int}` so we can handle backports

Just use a manually specified patch version

---

Makefile

Clean binaries before compiling.
Changing the OS/arch does not cause make to recompile binaries. This meant whichever arch was compiled first would then be used in place of all the others. Cleaning the binaries before compiling ensures we build for the correct arch.
1. Closes #194
Tested using `file build/amd64/*` and `file build/arm64/*` before and after the fix to ensure the binaries were for the correct architecture.

Ensure binaries are rebuilt when target changes.

---

docker/auto-setup.sh
docker/entrypoint.sh

Don't continue to start the Temporal Server if auto-setup.sh returns an error.
Improved the database driver validation error message.
Starting the server when auto-setup.sh found an error obscures the error message from auto-setup.sh, making it harder for users to understand what is wrong.
Also try to make it clearer that DB= sets the driver type, and report the valid values.
1. Closes 
Used the modified image to start badly configured containers and check the error reporting is clearer.

Don't ignore fatal errors from auto-setup.sh

---

.github/workflows/docker-build-only.yml

Bump `actions/upload-artifact` to `v4` in `.github/workflows/docker-build-only.yml`
https://github.com/temporalio/features/pull/491 bumped the download side to v4, but we also need to bump the upload side as well 
Should address errors like
```
Error: Unable to download artifact(s): Artifact not found for name: temporal-server-docker
```
example: https://github.com/temporalio/temporal/actions/runs/9424005363/job/25963539180?pr=6087
Note: I am only doing it for this workflow since I don't have context on how the other ones are used.
Should be safe to bump this since the only uses are in this repo and the main server repo https://github.com/search?q=org%3Atemporalio%20.github%2Fworkflows%2Fdocker-build-only.yml&type=code

Bump actions/upload-artifact to v4

---

.github/workflows/release-admin-tools.yml

This changes the admin-tools release workflow back to a simple "copy SHA tag" workflow (just like the one for server). It'll be the job of the release engineer to determine the correct tag.
AdminTools release workflow was trying to be too clever. 
1. Closes 

Simplify admin-tools release workflow

---

docker/entrypoint.sh

Set a sensible default for broadcast address if BIND_ON_IP is 0.0.0.0.
We require broadcast address to be set if listening on all interfaces, but it is not possible for users to know which IP they will have via environment variables on all platforms.
1. Closes 
Tested by two users on slack replacing their custom docker images that set TEMPORAL_BROADCAST_ADDRESS for them.
Also note this only sets TEMPORAL_BROADCAST_ADDRESS if it isn't already set and BIND_ON_IP=0.0.0.0 which is a known broken configuration anyway.

Default broadcast address to primary IP if binding on all interfaces

---

src/image_copy/main.go

Add verification step for Docker images before releasing them.
PS: I didn't add this to the _build_ step because the risk is high that it would fail silently without anyone noticing.
To ensure we release the right binary for each platform.
1. Closes 
Running from terminal:
**Pass**
```
DST_REPO=temporalio SRC_REPO=temporaliotest PASSWORD=wrong USERNAME=wrong IMAGES=server TAG=dummy COMMIT=bc8c2cd1928c4a6dd3330b48a370cf2c10672968 go run src/image_copy/main.go
verifying binaries in '/usr/local/bin' from 'temporaliotest/server:sha-bc8c2cd' for platform 'linux/arm64' are 'ARM'
Unable to find image 'temporaliotest/server:sha-bc8c2cd' locally
sha-bc8c2cd: Pulling from temporaliotest/server
Digest: sha256:aefb7a40c9bb176e96fb4611c3349631afe61a48b6094be551f2e475d9dccdd6 …
```

Verify binaries are for correct platform

---

docker/base-images/base-admin-tools.Dockerfile

Need to pin Python3 until the following issue is resolved, otherwise cqlsh wont work
https://issues.apache.org/jira/browse/CASSANDRA-19206
1. Closes 

Pin Python3 to 3.11 in base-admin-tools

---

docker/base-images/base-admin-tools.Dockerfile

Reverts temporalio/docker-builds#231
apk cannot install python 3.11 as it conflicts with the system-installed python 3.12.

Revert "Pin Python3 to 3.11 in base-admin-tools"

---

docker/base-images/base-admin-tools.Dockerfile

Alpine v3.20 comes with Python 3.12. But cqlsh won't work with Python 3.12 until the following issue is resolved.
https://issues.apache.org/jira/browse/CASSANDRA-19206
Compiling Python 3.11.9 from source and installing it on the side. Then creating a venv using that python version.
Revert this change once the issue mentioned above is resolved.
1. Closes 

Install Python 3.11.9 on base-admin-tools so cqlsh can run

---

docker/entrypoint.sh

It was implemented earlier for ipv4 only at https://github.com/temporalio/docker-builds/commit/527db58331aa95dc0f6816517e5502b95127192c
This commit adds support for ipv6

Default TEMPORAL_BROADCAST_ADDRESS to primary IP if BIND_ON_IP is ::1

---

docker/base-images/base-builder.Dockerfile
docker/base-images/base-ci-builder.Dockerfile

In #254 I accidentally references invalid `golang` images, this fixes the issue.

Fix base builder go images

---

docker/base-images/base-admin-tools.Dockerfile

Install `cqlsh` using `pipx` and dependencies to be build from source works with Python 3.12.
`cqlsh` with Python3.12 doesn't work out-of-box because `asyncore` module was removed from Python3.12, and the default built of `cqlsh` doesn't include the alternative `libev`.
However, it works if we can install it by building from source with libev (https://datastax-oss.atlassian.net/browse/PYTHON-1376).
1. Closes 

Simpler cqlsh installation in base-admin-tools image

---

docker/base-images/base-admin-tools.Dockerfile
docker/base-images/base-server.Dockerfile

Install `dockerize` in `base-server` image.
After a new image of `base-server` is released, I'll remove the `dockerize` submodule.
It was changed in https://github.com/temporalio/docker-builds/pull/190 to be build locally and only installed in the `server` and `auto-setup` images to be faster.
However, building and installing `dockerize` in `base-server` is quick (~8s locally linux/arm64), and `base-server` is not released often.
By doing this, we can remove the `dockerize` submodule.
1. Closes 

Install dockerize in base-server image

---

src/image_copy/main.go

Skip checking symlinks when checking binary files
When copying docker images from the `temporaliotest` registry to `temporalio`, it checks the binaries inside the container matches the respective platform architecture. However symlinks can't be verified with `file` command.
1. Closes 

Skip checking symlinks when checking binary files

---

docker/auto-setup.sh

only add custom search attributes if there was a default namespace
because search attributes depend on a namespace
1. Closes - nothing, just stumbled on the bug while fixing something else.
Samples-server repo
I don't think so.

only add custom search attributes if there was a default namespace

---

Makefile
admin-tools.Dockerfile
scripts/update-base-images.sh
server.Dockerfile

- Updated server and admin-tools to use our latest released base images
- Add a script and makefile target to do more of the same

Update Dockerfiles to use latest Temporal base, add a script to do it

---

.github/workflows/docker.yml
docker-bake.hcl

Fixed the HCL regex that's used for sanitizing the branch name to be an allowed Docker image tag.
Sanitization wasn't working. [[failed build](https://github.com/temporalio/docker-builds/actions/runs/16224800990/job/45814093495)]
Tested on this branch which is named `feature/Tes.ting+`:

Fix image branch tag sanitization

---

Makefile

Prevent the final digit of the git SHA from getting cut off
This was spreading the incorrect SHA to other cicd pipelines

Fix extraction of commit SHA for the cicd report

---

.github/CODEOWNERS

I removed the DevEx team. 
This is not a valid team in the temporalio organization, so its inclusion made the file invalid (as shown below). It was valid at the time that it was added, but was later renamed to `selfhosted`. However, Rob Holland and I recently discussed this and concluded that DevRel (of which selfhosted is a subset) should not be the owners. Consequently, removing the group resolves both issues.

Update CODEOWNERS to remove DevEx
