.github/workflows/update-submodules.yml
Adds pipeline that updates Temporal and TCTL submodules
Allows to automate submodules update for each Temporal and TCTL commit
1. Closes 
=> Add pipeline to update submodules

.github/workflows/docker-admin-tools.yml, .github/workflows/docker-auto-setup.yml, .github/workflows/docker-server.yml, auto-setup.Dockerfile, develop.Dockerfile, server.Dockerfile
Adds git sha env variable for temporal build
Temporal build uses the sha to set build metadata
1. Closes 
locally using `act`
=> Add git sha info for temporal build

.github/workflows/docker-admin-tools.yml, .github/workflows/docker-auto-setup.yml, .github/workflows/docker-server.yml
- Extracted docker --build-args construction into separate steps
- reused where needed
- removed incorrect syntax of commented out `latest` tag
- reusing script
- fix pipelines
1. Closes 
=> Extract build-args into separate reusable step

admin-tools.Dockerfile
Bumped admin-tools base images versions
newer versions
1. Closes 
=> Bump admin-tools base image versions

admin-tools.Dockerfile
Disables CGO for admin-tools image
removes dependency on `gcc` in $PATH and required for build to succeed
1. Closes 
built locally
=> Disable CGO for admin-tools image

auto-setup.Dockerfile, develop.Dockerfile, docker/auto-setup.sh, docker/base-images/Makefile, docker/base-images/README.md, docker/base-images/base-admin-tools.Dockerfile, docker/base-images/base-builder.Dockerfile, docker/base-images/base-ci-builder.Dockerfile, docker/base-images/base-server.Dockerfile, docker/entrypoint.sh, docker/setup-develop.sh, docker/start-temporal.sh, server.Dockerfile
Import Docker scripts from 
removing docker files from Temporal repo
1. Closes 
built auto-setup locally
=> Import Docker scripts

.github/workflows/docker-auto-setup.yml, .github/workflows/docker-server.yml
Dispatches action that results in CICD run
Triggering CICD for images built by Github Actions
1. Closes 
execute `docker-server` pipeline locally using `nektos/act`
=> Dispatch per-commit CICD

Makefile
Added few make scripts that build docker images
conveniece https://github.com/temporalio/temporal/pull/2456/files/980d8cf6acd268b0a5bfd7b6dc329b7fe30a944c#r799028776
1. Closes 
```
export DOCKER_IMAGE_TAG=test && make docker-server docker-auto-setup docker-admin-tools
```
=> Add make scripts that build docker images

.github/workflows/docker-admin-tools.yml, .github/workflows/docker-auto-setup.yml, .github/workflows/docker-server.yml
Executes Docker image build pipelines in PRs too (doesn't push image to Docker Hub)
Testing changes in PRs
1. Closes 
=> Execute Docker image build pipelines on PRs

.github/workflows/docker-admin-tools.yml, .github/workflows/docker-auto-setup.yml, .github/workflows/docker-server.yml, .github/workflows/update-submodules.yml
- Starts accepting Submodule name and Branch as the inputs (ex. `temporal`)
- Checks out and updates the submodule for a given branch (ex. `v1.1.0`)
- Commits the changes into a branch with the same name
Automating patch releases
1. Closes 
Tested the code with personal repos and simulating the changes:
https://github.com/feedmeapples/gha-parent
https://github.com/feedmeapples/gha-child
=> Allow updating particular branches

.github/workflows/docker-admin-tools.yml, .github/workflows/docker-auto-setup.yml, .github/workflows/docker-server.yml, README.md
Renamed Docker pipelines and steps (since they now sometimes only build and not push images)
In PRs images are just built, not pushed
Status badges will also look smaller than that:
1. Closes 
=> Rename Docker pipelines

.github/workflows/update-submodules.yml
Switches to Commander token to resolve the push access when updating submodules
Starts to update only the repo/submodule that triggered the pipeline 
Submodules update pipeline fails with permission issue
1. Closes 
not tested
=> Resolve permission issue when updating submodules

.github/workflows/scorecards.yml
Adds scorecards GHA security check and reporting
additional security
1. Closes 
=> Add scorecards for GHAs security check

docker/base-images/base-builder.Dockerfile, docker/base-images/base-ci-builder.Dockerfile, docker/base-images/base-server.Dockerfile
Upgrades base images to golang:1.18.0-alpine3.15
Upgrading some of dependent packages to go v1.18.0
1. Closes 
=> Upgrade base images to golang:1.18.0-alpine3.15

.github/workflows/release-base-image.yml
Corrected the image name & tag
from image name: `1.7.0`
to : `temporalio/base-builder:1.7.0`
image name & tag were set incorrectly, that results in push permission denial
1. Closes 
=> Fix Base-* images name:tag

.github/workflows/release-temporal.yml, .github/workflows/release.yml
Added a pipeline that allows to re-tag `server`, `admin-tools` and `auto-setup` images and push to temporalio
Facilitates release process
1. Closes 
executed with `act` `echo`ing the last skope line: 
```
| skopeo copy --all docker://temporaliotest/ui:b56843785892b64deae8f08d848ca8ae997c24dc docker://temporaliotest/ui:tag
| skopeo copy --all docker://temporaliotest/ui-test:b56843785892b64deae8f08d848ca8ae997c24dc docker://temporaliotest/ui-test
```
=> Create release pipeline

.github/workflows/release-base-image.yml
Allows selecting target architecture
base-ci-image doesn't build for arm64 because of missing dependencies
1. Closes 
ran locally with targets amd64 and arm64
=> Allow selecting target architecture for base images

.github/workflows/docker.yml
Added  `:latest` tag to Temporal docker images
:latest should always point to the most recent commit
1. Closes 
=> Add :latest tag to docker images

.github/workflows/docker.yml, Makefile, admin-tools.Dockerfile, develop.Dockerfile, server.Dockerfile
Upgrade go version to 1.18.
Keep go version up to date.
=> Upgrade go version to 1.18

.github/workflows/release-temporal.yml
Adds :latest to the Release Temporal images pipeline
to also update :latest image on each release
1. Closes 
=> Add :latest tag to release pipeline

.github/workflows/release-all-base-image.yml
Action to build and push all base images
Less clicky clicky
1. Closes 
Did my best using nektos/act
=> adding an action to release all base images

.github/workflows/release-all-base-image.yml
Removing default for input
Adding exclusion for invalid combination from matrix
Naming...
update tagging
Single workflow run will publish tags from the same image digest(s)
1. Closes 
=> Adjusting inputs and adding exclusion

docker/base-images/base-admin-tools.Dockerfile, docker/base-images/base-server.Dockerfile
Update server images to [alpine:3.15](https://hub.docker.com/layers/alpine/library/alpine/3.15/images/sha256-a777c9c66ba177ccfea23f2a216ff6721e78a662cd17019488c417135299cd89?context=explore).
Keep base images up to date.
=> Update server images to alpine:3.15

admin-tools.Dockerfile, server.Dockerfile
Update server and admin-tools images to the newer base images (alpine:3.15).
Keep server image up to date.
=> Update server and admin-tools images to the newer base images

server.Dockerfile
Copy single dynamic config file `docker.yaml` to the docker image.
Previously entire `dynamicconfig` dir were copied and it wasn't clear which config is used.
=> Copy single dynamic config file

docker/base-images/base-admin-tools.Dockerfile, docker/base-images/base-builder.Dockerfile, docker/base-images/base-ci-builder.Dockerfile, docker/base-images/base-server.Dockerfile
Update alpine and golang to the latest.
Closes #49.
=> Update alpine and golang to the latest

admin-tools.Dockerfile, server.Dockerfile
Update base image versions.
Keep dependencies up to date. See #51 for details.
=> Update base image versions

docker/auto-setup.sh
Use global `--db` flag for create database command.
To fix compatibility with https://github.com/temporalio/temporal/pull/2950.
=> Use global --db flag for create database command

admin-tools.Dockerfile
Include `tdbg` in `admin-tools` image.
`tdbg` is convinient tool to perform low level server debugging.
=> Include tdbg in admin-tools image

admin-tools.Dockerfile, server.Dockerfile
Bumped base-builder image to 1.10.0
Bumped base-server image to 1.11.0
Bumped base-admin-tools image to 1.7.0
Rolling out Golang 1.19
1. Closes 
CI
=> Bump base docker images

.github/workflows/release-temporal.yml, .github/workflows/update-latest-temporal.yml
Add job to update :latest docker tag.
Move latest to another tag.
I mostly copied from `release-temporal.yml`
=> Add job to update :latest docker tag

docker/base-images/base-admin-tools.Dockerfile
Pulled the latest `expat` version to mitigate security vulnerability: CVE-2022-40674
https://github.com/temporalio/temporal/issues/3459
1. Closes 
trivy
No
=> Pull the latest expat version to mitigate security vulnerability

admin-tools.Dockerfile
Bumped base-admin-tools image to 1.8.0
Mitigate security vulnerability: CVE-2022-40674
1. Closes 
https://github.com/temporalio/temporal/issues/3459
trivy
No
=> Bump admin-tools to mitigate security issue

admin-tools.Dockerfile, server.Dockerfile
Bumping base images
Releasing security patch for v1.18.4
1. Closes 
No
trivy, CI
No
=> Bump base image versions to address security issues

src/release_temporal/main.go
Fixed credentials assignment.
Typo
1. Closes 
No
CI
No
=> Fix credentials assignment

.github/CODEOWNERS
Added default repository code owners.
To assign code reviewers automatically.
1. Closes 
No
CI
No
=> Add repository CODEOWNERS

.gitmodules
explicitly added the branch name of Temporal CLI submodule 
attempt to fix pipelines
1. Closes 
=> Add branch for cli module

docker/auto-setup.sh
Replaced `tctl` with Temporal CLI.
`tctl` will be deprecated, and the commands needed to be updated for search attribute commands.
1. Closes 
* `make docker-auto-setup`
* `docker-compose up`
* Check the logs.
=> Update tctl commands to use Temporal CLI

docker/auto-setup.sh
Accept and handle `mysql8`, `postgres`, and `postgres12` plugin names.
Set up advanced visibility when plugin name is `mysql8` or `postgres12`.
1. Closes 
=> Support new DB values for advanced visibility in SQL

docker/base-images/base-builder.Dockerfile, docker/base-images/base-ci-builder.Dockerfile, docker/base-images/base-server.Dockerfile
Bumped base images
Use the latest versions to address security vulnerabilities
1. Closes 
No
CI
No
=> Bump base images

admin-tools.Dockerfile, server.Dockerfile
Bumped Docker image bases
To use the latest images
1. Closes 
No
CI
No
=> Bump Docker images bases

docker/auto-setup.sh
Support ES secondary visibility index.
https://github.com/temporalio/temporal/issues/3916
1. Closes https://github.com/temporalio/temporal/issues/3916
3. How was this tested:
Build docker container, and checked the secondary index in setup correctly.
=> Support ES secondary visibility index

admin-tools.Dockerfile, server.Dockerfile
Bumped base image versions.
Base images were rebuilt to address security vulnerabilities.
1. Closes 
No
CI
No
=> Bump base image version

docker/base-images/base-builder.Dockerfile
Added `curl` to base builder
Needed for https://github.com/temporalio/docker-builds/pull/112
1. Closes 
tested with https://github.com/temporalio/docker-builds/pull/112
=> Add curl to base-builder

.github/workflows/docker.yml
Fixed build-args definition.
It was wrong.
1. Closes 
No
CICD
No
=> Fix build-args definition

.github/workflows/release-all-base-image.yml, src/go.mod, src/go.sum, src/image_tags/main.go
Added automatic image tags bumping GHA.
Automation.
1. Closes 
No
CI
No
=> Automatically bump image tags

docker/base-images/base-admin-tools.Dockerfile
Fixed cqlsh installation for base-admin-tools image.
Bugfix.
1. Closes 
No
Locally
```
$ make base-admin-tools
...
$ docker run -it --rm temporalio/base-admin-tools:latest cqlsh -v
cqlsh 6.1.0
```
No
=> Fix cqlsh installation

.github/workflows/release-all-base-image.yml, src/image_tags/main.go
* Fixed GHA `image_tags` go run command.
* Send `image_tags` usage info to stderr.
Bugfix
1. Closes 
No
Locally, CI
No
=> Fix GHA action and send CLI Usage info to stderr

docker/base-images/base-admin-tools.Dockerfile, docker/base-images/base-builder.Dockerfile, docker/base-images/base-ci-builder.Dockerfile, docker/base-images/base-server.Dockerfile
Bumped the Alpine version to 3.18
Have the latest version.
1. Closes 
No
CICD
No
=> Bump temporal-base images Alpine version to 3.18

.github/workflows/release-all-base-image.yml
Removed Commit tag from released images.
We don't need Commit tags for releases. 
1. Closes 
No
GHA
No
=> Don't publish commit tag

docker/base-images/base-admin-tools.Dockerfile
Added `yq` to the base-admin-tools image.
We are expanding tools collection.
1. Closes 
No
CICD
No
=> Add yq to the base-admin-tool image

.github/workflows/update-submodules.yml
Update token management to use Github App instead
Update token management to use GitHub App instead
Switching to the org-level token management
1. Closes 
No
CI
No
=> Update update-submodules GHA token management

.github/workflows/docker.yml
Update token management to use Github App instead
Switching to the org-level token management
1. Closes 
No
CI
No
=> Update docker GHA tokens

.github/workflows/docker.yml, .github/workflows/update-latest-temporal.yml, .github/workflows/update-submodules.yml
Update GHA permissions
To allow only what's required.
1. Closes 
No
GHA
No
=> Update GHA permissions

admin-tools.Dockerfile, server.Dockerfile
Update base-builder images in `server.Dockerfile` and `admin-tools.Dockerfile` that uses Go 1.20.10.
Address https://www.nginx.com/blog/http-2-rapid-reset-attack-impacting-f5-nginx-products/
1. Closes 
=> Update base builder versions

.github/workflows/docker.yml
- Allow manually trigger the docker image build.
- Only update latest tag when there’s a push to main.
1. Closes 
=> Improve Build Docker Images GHA

.github/workflows/docker.yml
This reverts commit 0ee04861cca8669955a359571ad0f074a4ebf14b.
1. Closes 
=> Revert "Improve Build Docker Images GHA (#159)"

.github/workflows/docker.yml, docker-bake.hcl
This is my fault but I'm going to blame my reviewer because I find that amusing.
(I don't actually blame them)
=> Reinstate linux/arm64 build

.github/workflows/docker.yml, Makefile
I added a workflow_dispatch trigger for our main release action
=> Add workflow_dispatch trigger for main build-push-images workflow

docker/auto-setup.sh
Remove Cassandra visibility set up.
Fix plugin name when setting up MySQL and PostgreSQL.
Support for Cassandra visibility is being deprecated.
1. Closes 
=> Remove Cassandra visibility

admin-tools.Dockerfile, server.Dockerfile
=> Update base images

docker-compose.yml, docker/auto-setup.sh
Remove standard visibility support
1. Closes 
=> Remove standard visibility support

.github/workflows/release-all-base-image.yml, .github/workflows/release-base-image.yml, docker/base-images/base-builder.Dockerfile, docker/base-images/base-ci-builder.Dockerfile, docker/base-images/base-server.Dockerfile
I bumped the version of golang we're using and changed our alpine tag to 3 from 3.19.
I also changed our base-* actions to forcibly pull the latest version of their dependencies
=> Update our base images

.github/workflows/docker-build-only.yml, .github/workflows/docker.yml, .github/workflows/lint.yml, .github/workflows/release-all-base-image.yml, .github/workflows/release-base-image.yml, .github/workflows/release-temporal.yml, .github/workflows/update-submodules.yml
Reverts temporalio/docker-builds#195
=> Revert "Update GHA versions so CI stops complaining"

.github/workflows/docker-build-only.yml
I missed a spot when I changed all this
=> Setup go locally in build-only workflow

.github/workflows/docker-build-only.yml, .github/workflows/features-integration.yml, test.sh
We now run our feature tests on PRs and commits to main.
While we run feature tests in the server repo we don't run them here, meaning image configuration changes can break the build in the server repo.
Let's catch that before it happens
=> Run feature tests on changes

admin-tools.Dockerfile
=> Bump admin-tools base image

.github/workflows/release-admin-tools.yml, .github/workflows/release-temporal.yml
=> Its admin-tools, not admintools

docker-readme/auto-setup.md
@robholland how's this looking for a start? can push to dockerhub when complete
=> start adding docker readme for auto-setup

src/go.mod, src/go.sum, src/image_copy/main.go
Checking the binaries without _running_ the Docker container.
Example output:
```
verifying binaries in '/usr/local/bin' from 'temporaliotest/admin-tools:sha-05ac5b8' for platform 'linux/arm64' are 'ARM'
>  docker create --name bGludXgvYXJtNjQtMTcyMDcxOTk3MDU0OQ --platform linux/arm64 temporaliotest/admin-tools:sha-05ac5b8
Unable to find image 'temporaliotest/admin-tools:sha-05ac5b8' locally
sha-05ac5b8: Pulling from temporaliotest/admin-tools
Digest: sha256:3dc1f7ae18a0382d57cd6f75d69bfba4cce7b2f31199a9d097c411afc7b38c7d
Status: Downloaded newer image for temporaliotest/admin-tools:sha-05ac5b8
e22bfda97164763452dfbac597767d427e434571cd1c69598cb943259d5a7373
>  docker cp bGludXgvYXJtNjQtMTcyMDcxOTk3MDU0OQ:/usr/local/bin/. /var/folders/4w/5qdjw8sd6417nldg5pvhs_rr0000gn/T/bGludXgvYXJtNjQtMTc …
```
=> Fix platform verification

.github/workflows/release-admin-tools.yml, .github/workflows/release-temporal.yml
Set working dir for Go program execution.
https://github.com/temporalio/docker-builds/pull/228 added a Go dependency, but the GHA was invoking the Go program incorrectly.
1. Closes 
=> Fix working dir

docker/base-images/base-admin-tools.Dockerfile, docker/base-images/base-builder.Dockerfile, docker/base-images/base-ci-builder.Dockerfile, docker/base-images/base-server.Dockerfile
Bumped Alpine version from 3.19 -> 3.20
1. Closes 
=> Upgrade base images to Alpine 3.20

docker/base-images/base-builder.Dockerfile, docker/base-images/base-ci-builder.Dockerfile
=> update go to 1.23

admin-tools.Dockerfile, server.Dockerfile
Update base image to get the latest Alpine patches.
1. Closes 
=> Upgrade server and admin-tools to base image 1.15.9

admin-tools.Dockerfile, server.Dockerfile
Update to latest base images to get recent Alpine patches.
1. Closes 
=> [1.25 branch] Upgrade server and admin-tools to base image 1.15.9

admin-tools.Dockerfile, docker/base-images/README.md, docker/base-images/base-builder.Dockerfile, docker/base-images/base-ci-builder.Dockerfile
Run `apk upgrade` in base builder images.
Updating the packages can address CVE in old versions.
1. Closes 
=> Run apk upgrade in base builder images

.gitmodules, Makefile, admin-tools.Dockerfile, server.Dockerfile
Remove dockerize submodule
Less dependency as submodule
1. Closes 
=> Remove dockerize submodule

.github/workflows/docker.yml
Use latest version of docker/login-action, go from v1 to v3
Code janitorial services 🧹 
1. Closes 
=> Use latest version of docker/login-action
